config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  # sessions manipulation
  get    'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'


  get    'signup'                          => 'users#new'
  get    'user/settings'                   => 'users#edit',   as: :user_settings
  patch  'user/settings'                   => 'users#update', as: :user_update
#  resources :users, except: [:edit] do
#    member do
#      get :following, :followers
#    end
#    collection do 
#      resources :account_activations, only: [:edit]
#      resources :password_resets,     only: [:new, :create, :edit, :update]
#    end
#  end 

  #get   'dashboard'   => 'dashboard#index'

  resources :devices do
    member do
      get 'alerts'      => 'devices#alerts'
    end
  end

  resources :coords

  #resources :apis
  get    'api/:device_id/:state/:lat/:lng/:time' => 'apis#report', as: :api
  get    'api/go'       => 'apis#go'
  get    'api/goriver'  => 'apis#goriver'
  get    'api/clean'    => 'apis#clean'

  ## omni auth add-on
  #get '/auth/:provider/callback'  => 'sessions#omniauth_endpoint'
  #get '/login/facebook'           => 'sessions#facebook', as: :facebook_login
  ##get '/signout'                  => 'sessions#destroy',  as: :signout
  #get '/auth/failure'             => 'sessions#failure'

end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :user

  has_many :coords

  
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :alerts, :edit, :update, :destroy]
  before_action :logged_in_user

  # GET /devices
  # GET /devices.json
  def index
    @devices = current_user.devices
  end

  def show
  end

  def alerts
  end

  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:name, :user_id)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Save Settings', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/devices/alerts.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', devices_path %>

<h1><%= @device.name %> <%= link_to raw('<span class="glyphicon glyphicon-pencil"></span>'), edit_device_path(@device), class: 'btn btn-primary btn-sm' %></h1>

<%= link_to 'Journies', device_path(@device), class: 'btn btn-primary btn-lg' %>
<%= link_to 'Alerts',  alerts_device_path(@device), class: 'btn btn-primary btn-lg active' %>

<h3>Last alert</h3>
<% unless @device.coords.where(state: 'alert').empty? %>
  <% created_at = @device.coords.where(state: 'alert').last.created_at %>
  <!-- <p><strong><big><%= Time.at( @device.coords.where(state: 'alert').last.created_at ).strftime("%B %e, %Y at %l:%M %p") unless @device.coords.where(state: 'alert').last.created_at.nil?  %></big></strong></p> -->
  <p><strong><big><%= time_ago_in_words(Time.at(created_at)) + " ago" unless created_at.nil? %></big></strong></p>
<% end %>

<div id="map-container">
  <div id="map-canvas"></div>
</div>

<h3>Alert History</h3>
<ul>
  <% @device.coords.where(state: 'alert').reverse_each do |c| %>
    <li><%= c.created_at.nil? ? '--' : Time.at( c.created_at ).strftime("%B %e, %Y at %l:%M %p") %></li>
  <% end %>
</ul>



<% content_for :js do %>
<script>
  function localMapChanges()
  {
    <% c = @device.coords.where(state: 'alert').last %>
    createCustomMarker(<%= c.lat %>, <%= c.lng %>, map, "Time: <%= Time.at( c.created_at ).to_datetime.strftime("%B %e, %Y at %l:%M %p") unless c.created_at.nil? %>")
  }
</script>
<% end %>

<%# Not using the below since we are only interested in the last alert %>
<%
=begin
%>
    <% @device.coords.where(state: 'alert').each do |c| %>
      //createMarker(<%= c.lat %>, <%= c.lng %>, map, 'Time:')
      // createCustomMarker(<%= c.lat %>, <%= c.lng %>, map, "Time: <%= Time.at( c.created_at ).to_datetime.strftime("%B %e, %Y at %l:%M %p") unless c.created_at.nil? %>")
    <% end %>
<%
=end
%>

app/views/devices/edit.html.erb
<%= link_to 'Back', devices_path %>

<h1>Joyride Settings</h1>

<%= render 'form' %>

<%#= link_to 'Show', @device %>

app/views/devices/index.html.erb
<h1>Your Joyrides</h1>

<% @devices.each do |device| %>
  <%= link_to raw("<span class='glyphicon glyphicon-cd'></span> #{device.name}"), device, class: 'btn btn-primary btn-lg' %>
  <br /><br />
  <%= link_to raw("<span class='glyphicon glyphicon-cd'></span> Add Joyride"), new_device_path, class: 'btn btn-primary btn-lg ghost' %>
<% end %>


<br>



<br />
<br />

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', devices_path %>

<h1><%= @device.name %> <%= link_to raw('<span class="glyphicon glyphicon-pencil"></span>'), edit_device_path(@device), class: 'btn btn-primary btn-sm' %></h1>

<%= link_to 'Journies', device_path(@device), class: 'btn btn-primary btn-lg active' %>
<%= link_to 'Alerts',  alerts_device_path(@device), class: 'btn btn-primary btn-lg' %>

<h3>Last journey</h3>
<p>Avg Speed <strong><big>12 km/h</big></strong></p>
<p>Calories burned <strong><big>400 cal</big></strong></p>

<div id="map-container">
  <div id="map-canvas"></div>
</div>

<h3>Journey History</h3>
<ul>
  <% @device.coords.where(state: 'journey').reverse_each do |c| %>
    <li>Time: <%= c.created_at.nil? ? '--' : Time.at( c.created_at ).to_datetime.strftime("%B %e, %Y at %l:%M %p") %></li>
  <% end %>
</ul>


<% content_for :js do %>
<script>
  function localMapChanges()
  {
    map.setZoom(14);

    //createMarker(<%= @device.coords.where(state: 'journey').last.lat %>, <%= @device.coords.where(state: 'journey').last.lng %>, map, 'Last Position')
    createCustomMarker(<%= @device.coords.where(state: 'journey').last.lat %>, <%= @device.coords.where(state: 'journey').last.lng %>, map, 'Last Position')

    // make a path with start and end points
    var lineCoordinates = []
    <% @device.coords.where(state: 'journey').each do |c| %>
      //createMarker(<%= c.lat %>, <%= c.lng %>, map, 'Time:')
      lineCoordinates.push(new google.maps.LatLng(<%= c.lat %>, <%= c.lng %>))
      createCustomMarker(<%= c.lat %>, <%= c.lng %>, map, "Time: <%= Time.at( c.created_at ).to_datetime.strftime("%B %e, %Y at %l:%M %p") unless c.created_at.nil? %>")
    <% end %>

    createPolyline(map, lineCoordinates, lineSymbol);
  }
</script>
<% end %>