config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  # sessions manipulation
  get    'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'


  get    'signup'                          => 'users#new'
  get    'user/settings'                   => 'users#edit',   as: :user_settings
  patch  'user/settings'                   => 'users#update', as: :user_update
#  resources :users, except: [:edit] do
#    member do
#      get :following, :followers
#    end
#    collection do 
#      resources :account_activations, only: [:edit]
#      resources :password_resets,     only: [:new, :create, :edit, :update]
#    end
#  end 

  #get   'dashboard'   => 'dashboard#index'

  resources :devices do
    member do
      get 'alerts'      => 'devices#alerts'
    end
  end

  resources :coords

  #resources :apis
  get    'api/:device_id/:state/:lat/:lng/:time' => 'apis#report', as: :api
  get    'api/go'       => 'apis#go'
  get    'api/goriver'  => 'apis#goriver'
  get    'api/clean'    => 'apis#clean'

  ## omni auth add-on
  #get '/auth/:provider/callback'  => 'sessions#omniauth_endpoint'
  #get '/login/facebook'           => 'sessions#facebook', as: :facebook_login
  ##get '/signout'                  => 'sessions#destroy',  as: :signout
  #get '/auth/failure'             => 'sessions#failure'

end

app/models/api.rb
class Api < ActiveRecord::Base
end

app/controllers/apis_controller.rb
require 'twilio-ruby'

class ApisController < ApplicationController
#  before_action :set_api, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token


  def report
    # API call: /api/:device_id/:state/:lat/:long/:time/
    alert(params[:device_id], params[:state], params[:lat], params[:lng], params[:time])
    
    #render :nothing => true, :status => 200, :content_type => 'text/html'
    render text: 'ok'
    return
  end

  def go
    #
    # Test coordinates
    # Mars building: 43.6598912, -79.3886251
    # Riverdale: 43.658010 -79.377507
    # 
    lat = '43.6598912'
    lng = '-79.3886251'

    lat_str = ( (lat.to_f + 90.to_f) * 1000000.to_f ).to_i
    lng_str = ( (lng.to_f + 180.to_f) * 1000000.to_f ).to_i

    alert(1, 2, lat_str, lng_str, Time.now.to_i)

    render text: 'ok'
    return
  end

  def goriver
    #
    # Test coordinates
    # Riverdale: 43.659891 -79.358625
    # 
    lat = '43.659891'
    lng = '-79.358625'

    lat_str = ( (lat.to_f + 90.to_f) * 1000000.to_f ).to_i
    lng_str = ( (lng.to_f + 180.to_f) * 1000000.to_f ).to_i

    alert(1, 2, lat_str, lng_str, Time.now.to_i)

    render text: 'ok'
    return
  end

  def clean
    Coord.destroy_all(state: 'alert')

    render text: 'good'
    return
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def api_params
      params[:api]
    end

    def alert(device_id, state_code, lat_str, lng_str, time)
      if Device.exists?(device_id)
        @device = Device.find(device_id)
        if [1,2].map{|i| i.to_s }.include?(state_code.to_s)
          case state_code.to_s
            when 1.to_s
              state = 'journey'
            when 2.to_s
              state = 'alert'
          end

          # store the stuff
          lat = (lat_str.to_f / 1000000.to_f) - 90
          lng = (lng_str.to_f / 1000000.to_f) - 180

          epoch = Time.now.to_i

          c = Coord.new(device: @device, state: state, lat: lat, lng: lng, epoch: epoch)
          c.save

          # if this was an alert, send a email or text
          unless @device.user.text_notification.blank?
            # send a message to Twilio (with a google map link?)
            to_number = Rails.env.production? ? '+14164001810' : '+14168418601'

            #https://www.google.ca/maps/search/43.6598912,+-79.3886251/@43.6598912,-79.3886251,17z/data=!3m1!4b1?hl=en
            #https://www.google.ca/maps/search/#{lat},+#{lng}/@#{lat},#{lng},17z/data=!3m1!4b1?hl=en
            url = "https://www.google.ca/maps/search/#{lat},+#{lng}/@#{lat},#{lng},17z/data=!3m1!4b1?hl=en"
            #url = Googl.shorten("https://www.google.ca/maps/search/#{lat},+#{lng}/@#{lat},#{lng},17z/data=!3m1!4b1?hl=en")

            $twilio_client.account.messages.create(
                :from => $twilio_phone_number,
                :to => to_number,
                :body => "Your Joyride has detected unexpected movement. #{Time.now.strftime("%I:%M %P")} \n #{url}"
              )

          end

        end
      end
    end
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/views/apis/_form.html.erb
<%= form_for(@api) do |f| %>
  <% if @api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api.errors.count, "error") %> prohibited this api from being saved:</h2>

      <ul>
      <% @api.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apis/edit.html.erb
<h1>Editing api</h1>

<%= render 'form' %>

<%= link_to 'Show', @api %> |
<%= link_to 'Back', apis_path %>

app/views/apis/index.html.erb
<h1>Listing apis</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apis.each do |api| %>
      <tr>
        <td><%= link_to 'Show', api %></td>
        <td><%= link_to 'Edit', edit_api_path(api) %></td>
        <td><%= link_to 'Destroy', api, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Api', new_api_path %>

app/views/apis/new.html.erb
<h1>New api</h1>

<%= render 'form' %>

<%= link_to 'Back', apis_path %>

app/views/apis/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_api_path(@api) %> |
<%= link_to 'Back', apis_path %>