config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  # sessions manipulation
  get    'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'


  get    'signup'                          => 'users#new'
  get    'user/settings'                   => 'users#edit',   as: :user_settings
  patch  'user/settings'                   => 'users#update', as: :user_update
#  resources :users, except: [:edit] do
#    member do
#      get :following, :followers
#    end
#    collection do 
#      resources :account_activations, only: [:edit]
#      resources :password_resets,     only: [:new, :create, :edit, :update]
#    end
#  end 

  #get   'dashboard'   => 'dashboard#index'

  resources :devices do
    member do
      get 'alerts'      => 'devices#alerts'
    end
  end

  resources :coords

  #resources :apis
  get    'api/:device_id/:state/:lat/:lng/:time' => 'apis#report', as: :api
  get    'api/go'       => 'apis#go'
  get    'api/goriver'  => 'apis#goriver'
  get    'api/clean'    => 'apis#clean'

  ## omni auth add-on
  #get '/auth/:provider/callback'  => 'sessions#omniauth_endpoint'
  #get '/login/facebook'           => 'sessions#facebook', as: :facebook_login
  ##get '/signout'                  => 'sessions#destroy',  as: :signout
  #get '/auth/failure'             => 'sessions#failure'

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <%= debug(params) if Rails.env.development? %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('header-logo.png'), root_path, class: 'navbar-brand', title: 'Joyride' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li class="devices <%= 'active' if params[:controller] == 'devices' %>"><%= link_to 'Devices', devices_path %></li>
        <% end %>
        <% if Rails.env.development? %>
          <li><%= link_to "Routes", '/rails/info/routes' %></li>
        <% end %>
      </ul>
<%#      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
%>
  
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <%# <li><a href="#">Link</a></li> %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Settings', user_settings_path %></li>
              <li class="divider"></li>
              <li><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=raw full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body <%=raw body_class(yield(:bodyclass)) %>>
<div id="wrap">

<%= render 'layouts/header' %>

<div class="contents">
  <% flash.each do |message_type, message| %>
    <div class="flash-container">
      <div class="container">
        <div class="alert alert-<%= message_type %>"><%=raw message %></div>
      </div>
    </div>
  <% end %>

  <div class="container">
    <div class="well">
      <%= yield %>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

</div>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<%# Output any JS that was provided in a view %>
<%= yield(:js) %>

</body>
</html>